### ISSUE TITLE
require.js has syntax error

### ISSUE THREAD

**Issue by sidarth164** [mslabina/sfmc-servicecloud-customsplit#1]
Markus, thanks for the example on custom activity split. But, I think that require.js file has syntax error. Also, since there is no indentation, I have no way of debugging it (I checked the syntax online). Please do upload a correct version of require.js file.

**Comment by mslabina** [comment]
Require.js is an external library, so please raise an issue on their project (https://github.com/requirejs/requirejs) if you found an error. However I am using this very file without any issues.

**Comment by sidarth164** [comment]
Actually, just by inserting endlines at two positions (where regular expression was mentioned), the error was resolved. I think that without the endline, ' & " were being treated as strings rather than component of a regular expression.
